schema = "app"
on_schema_exists = "recreate"
unlogged_tables = true
preserve_defaults = false
add_unsigned_checks = false
replicate_on_update_current_timestamp = false
workers = 8

[mysql]
dsn = "root:root@tcp(127.0.0.1:3306)/source_db"

[postgres]
dsn = "postgres://postgres:postgres@127.0.0.1:5432/target_db?sslmode=disable"

[type_mapping]
tinyint1_as_boolean = false
binary16_as_uuid = false
datetime_as_timestamptz = false
json_as_jsonb = false
sanitize_json_null_bytes = true
unknown_as_text = false

[hooks]
before_data = []
after_data = []
before_fk = []
after_all = []
