schema = "sakila"
on_schema_exists = "error"
source_snapshot_mode = "none"
unlogged_tables = false
clean_orphans = true
preserve_defaults = true
add_unsigned_checks = false
replicate_on_update_current_timestamp = false
workers = 4

[source]
type = "mysql"
dsn = "root:root@tcp(127.0.0.1:3306)/sakila"

[target]
dsn = "postgres://postgres:postgres@127.0.0.1:5432/sakila"

[type_mapping]
tinyint1_as_boolean = false
binary16_as_uuid = false
datetime_as_timestamptz = false
json_as_jsonb = false
enum_mode = "text"
set_mode = "text"
sanitize_json_null_bytes = true
unknown_as_text = false

[hooks]
before_data = []
after_data = []
before_fk = ["cleanup.sql"]
after_all = ["post.sql"]
